version: "3.9"

services:
  web:
    build: .
    container_name: flixcinema_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=movie_booking

  db:
    image: mysql:8.0
    container_name: flixcinema_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_booking
    volumes:
      - db_data:/var/lib/mysql
      - ./cinema_booking.sql:/docker-entrypoint-initdb.d/cinema_booking.sql

volumes:
  db_data:
